# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"echo "# hashim20.10-hotmail.com" >> README.md 
git init 
git add README.md 
git commit -m "ilk taahhüt" 
git branch -M main 
git remote add Origin https://github.com/Hashimmaaix/ hashim20.10-hotmail.com.git
 git push -u kökenli ana
